version: "2"

services:
  build-rpm:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/builders/puppet:${IMAGE_VERSION_TAG}
    entrypoint: /etc/init.d/build-rpm.sh
    volumes:
      - "./:${BUILD_DIR}"
    environment:
      - BUILD_DIR=${BUILD_DIR}
  develop:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/builders/puppet:${IMAGE_VERSION_TAG}
    entrypoint: /etc/init.d/develop.sh
    volumes:
      - "./puppet:/etc/puppetlabs/code/environments"
    environment:
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_MFA_EXPIRY=${AWS_MFA_EXPIRY}
      - AWS_REGION=${AWS_REGION}
      - DEBUG=${DEBUG}
      - ROLE=${ROLE}
  package-modules:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/builders/puppet:${IMAGE_VERSION_TAG}
    entrypoint: /etc/init.d/package-modules.sh
    volumes:
      - "./:${BUILD_DIR}"
    environment:
      - BUILD_DIR=${BUILD_DIR}